### ISSUE TITLE
FLEx 005 - preprocessing error

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#83]
The preprocessing script fails on FLEx 005:
~~~~
Nicholas-Tomlins-MacBook-Pro:preprocessing Nicholas$ node preprocess_flex.js 
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property '0' of undefined
    at /Users/Nicholas/GitHub/Korpus/preprocessing/preprocess_flex.js:145:49
    at Parser.<anonymous> (/Users/Nicholas/GitHub/Korpus/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at SAXParser.onclosetag (/Users/Nicholas/GitHub/Korpus/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/Users/Nicholas/GitHub/Korpus/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/Nicholas/GitHub/Korpus/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/Nicholas/GitHub/Korpus/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/Users/Nicholas/GitHub/Korpus/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/Users/Nicholas/GitHub/Korpus/node_modules/xml2js/lib/xml2js.js:508:31)
~~~~
It cites this line of our code:
~~~~
var paragraph = wrappedParagraph.phrases[0].word; // ERROR: kalinda pls fix
~~~~

**Comment by sciepsilon** [comment]
Closed in e866d22.
